version: 0.0
os: linux


files:
  - source: boot.war
    destination: /opt/tomcat/tomcat-10/webapps/
    overwrite: yes



permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: Scripts/deploy/deploy.sh
      timeout: 60
<<<<<<< HEAD
      runas: ubuntu
=======
      runas: ubuntu
>>>>>>> b33448d514d27db38836cfb8422c9177347d27a2
